"""The capability matrix.

Run against a plugin plus the reference harnesses, the output tells a plugin author the one
thing a pass/fail list cannot: whether a failure is theirs or the format's. If Parquet and IPC
lose it too, it is inherent; if they keep it, it is a bug.

It doubles as user-facing documentation of the plugin's limits, which is worth the formatting
effort.
"""

from __future__ import annotations

from collections import defaultdict
from collections.abc import Iterable, Sequence
from dataclasses import dataclass
from enum import Enum

from plioc import oracle
from plioc.corpus import all_cases
from plioc.harness import IOHarness, identity, is_failure
from plioc.spec import CaseSpec


class Outcome(Enum):
    PASS = "pass"
    LOSSY = "lossy"
    XFAIL = "xfail"
    SKIP = "skip"
    FAIL = "fail"

    @property
    def mark(self) -> str:
        return {"pass": "OK", "lossy": "~", "xfail": "xfail", "skip": "-", "fail": "FAIL"}[
            self.value
        ]


@dataclass(frozen=True)
class Cell:
    outcome: Outcome
    detail: str = ""


def evaluate(harness: IOHarness, case: CaseSpec) -> Cell:
    caps = harness.capabilities()
    declared = caps.known_failures.get(case.id)
    for _name, dtype in case.schema().items():
        if not caps.supports(dtype):
            return Cell(Outcome.SKIP, f"{dtype} not claimed")
    try:
        oracle.check_roundtrip(harness, case)
    except BaseException as exc:  # noqa: BLE001 - a cell value, not a crash; a panic counts too
        if not is_failure(exc):
            raise
        if declared is not None:
            return Cell(Outcome.XFAIL, declared)
        return Cell(Outcome.FAIL, f"{type(exc).__name__}: {exc}".splitlines()[0][:120])
    if declared is not None:
        return Cell(Outcome.FAIL, f"declared a known failure ({declared}) but passes")
    lossy = caps.normalize is not identity
    return Cell(Outcome.LOSSY if lossy else Outcome.PASS, "normalised" if lossy else "")


def render(
    harnesses: Sequence[IOHarness],
    cases: Iterable[CaseSpec] | None = None,
    *,
    include_slow: bool = False,
) -> str:
    if cases is None:
        # `query/fixture` exists to be queried, not to be round-tripped, and it holds a column of
        # every kind -- so one unsupported dtype would show the whole row as unsupported and say
        # nothing about the ten columns that work.
        cases = [
            c for c in all_cases(include_slow=include_slow).values() if "query" not in c.all_tags
        ]
    cases = list(cases)
    grid: dict[str, dict[str, Cell]] = defaultdict(dict)
    for case in cases:
        for harness in harnesses:
            grid[case.id][harness.name] = evaluate(harness, case)

    by_tag: dict[str, list[CaseSpec]] = defaultdict(list)
    for case in cases:
        for tag in sorted(case.all_tags) or ["untagged"]:
            by_tag[tag].append(case)

    lines = [
        "# Capability matrix",
        "",
        "Generated by `plioc.report`. `OK` round-trips exactly at the declared strictness; `~`",
        "round-trips through the harness's declared normalisation; `xfail` is a declared known",
        "failure; `-` is a dtype the harness does not claim; `FAIL` is undeclared and is a bug.",
        "",
    ]
    names = [h.name for h in harnesses]
    for tag in sorted(by_tag):
        lines += [
            f"## {tag}",
            "",
            "| case | " + " | ".join(names) + " |",
            "|---|" + "---|" * len(names),
        ]
        for case in by_tag[tag]:
            row = [grid[case.id][name].outcome.mark for name in names]
            lines.append(f"| `{case.id}` | " + " | ".join(row) + " |")
        lines.append("")

    failures = [
        (cid, name, cell)
        for cid, row in grid.items()
        for name, cell in row.items()
        if cell.outcome is Outcome.FAIL
    ]
    if failures:
        lines += ["## Undeclared failures", ""]
        for cid, name, cell in sorted(failures):
            lines.append(f"- `{cid}` / **{name}**: {cell.detail}")
        lines.append("")
    return "\n".join(lines)


def main() -> None:  # pragma: no cover - a convenience entry point
    """`python -m plioc.report [OUT.md] [module:Factory ...]`

    Each extra argument names a callable taking a root directory and returning a harness, so a
    plugin's matrix is rendered beside the reference formats -- which is the whole point of the
    document. With none, only the reference harnesses are rendered.
    """
    import sys
    from importlib import import_module
    from pathlib import Path
    from tempfile import TemporaryDirectory

    from plioc.harnesses.files import IpcHarness, ParquetHarness
    from plioc.harnesses.memory import MemoryHarness
    from plioc.harnesses.plugin import PluginHarness

    args = sys.argv[1:]
    out = Path(args[0]) if args and ":" not in args[0] else Path("CAPABILITIES.md")
    factories = [a for a in args if ":" in a]

    with TemporaryDirectory() as tmp:
        root = Path(tmp)
        harnesses: list[IOHarness] = [
            MemoryHarness(),
            PluginHarness(),
            ParquetHarness(root / "parquet"),
            IpcHarness(root / "ipc"),
        ]
        for spec in factories:
            module, _, attr = spec.partition(":")
            factory = getattr(import_module(module), attr)
            harnesses.append(factory(root / attr.lower()))
        text = render(harnesses)

    out.write_text(text, encoding="utf-8")
    print(f"wrote {out}")


if __name__ == "__main__":  # pragma: no cover
    main()
